### ISSUE TITLE
Proposal Feedback

### ISSUE THREAD

**Issue by evhumphrey** [lockjohn/eventdark#1]
# Eventdark Feedback

Well done overall!

## Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments:

Awesome! Just missing a placeholder heroku link.

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments:

Well done overall, I would add a bit more description to each feature (what it is, what are the CRUD (create read update destroy) actions on it related to users, like "Users can create and delete bookmarks for events". 

---

# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
## Comments:

- You’ll be using [ActiveStorage](https://github.com/rails/rails/tree/master/activestorage) for handling storing images, and won't need to store the url in your db (you can access it via an association).
- What is `organizer_description` in the `users` table? (Note: reading further, I think it's the description of the user, correct? If so, I would just call it `description`).
- In `events` table, instead of storing `availability`, I would store a `capacity` field and count the number of attendes (via an association, like event.attendes or something). You could then check anytime you were processing a request that if the tickets requested > capacity - reservations, you wouldn't allow it. There's some interesting stuff here! You could have a way to temporarily 'hold' reservations/tickets until the checkout is complete; that way, you can avoid two people who might try to book the last ticket at the same time (this isn't required, thinking outloud here)
- I would not make `event_type` an array; what does `event_type` represent? Is this different from categories?
- I wouldn't worry about `followings` for MVP (but leave it in, it can be something you do for a bonus!)
- Would list foreign keys and associations after each table.

---

# Routes

- [x] Routes accurately reflect MVPs and Component Hierarchy
- [x] Covers the frontend functionality of the site
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint bc that info comes through the post show
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments:

- BACKEND:
  - `GET /api/users` might be uneccessary; you can fetch organizers when you fetch events (as they are associated) 
  - `PATCH /api/events/:id` has a little note `need` 
  - Markdown error on `categories`
  - I think there are typos under `registration`, mentions follow an organizer, but these endpoints should be for RSVP / un-RSVPing.
  - No need to worry about followings for MVP. 
- FRONTEND:
  - The formatting looks a bit strange (a lot of bullet points)
  - You have a lot of components in here, some seem uncessary (at least for MVP)
---

# Sample State
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema (Ex: if you create a `imgUrl` key in the state, make sure your database also has a column that contains an `img_url`)
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice
    
## Comments:

- Awesome job on this!
- Dont have followers for now (again, this can be a bonus)
- Also, event_type seems like it could be stored differently, related to how we set it up in the backend

**Comment by lockjohn** [comment]
1.  Homepage- added live page link
2. MVP - updated features with CrUD actions
3. db Schema:
-removed  photo_url column from users table
-on eventbrite, users can signup to be organizers and create events, and a description of that user's organizer activities (usually under auspices of a event producing business) appears on every event that user organizes. regular users do not have descriptions in their profiles. ->Changed to 'description'
-changed event column from 'availability' to 'capacity'
-on eventbrite, events are described by category (Arts, Music, Business...) and event type (Performance, Class, Gala...); on the event show page these are listed as 'tags', but on search page they are listed separately as search filters (can use one or both). Both are chosen from a list of predetermined options, thus I was thinking of using an array, but can just make string and restrict by input method. Will move category aka event topics column to events table and do away with category table and joins table 'tagging'.  ->moved categories to events column, removed categories table and taggings join table
-added forgien keys and associations
4. Backend Routes:
-fixed formatting on page, updated to reflect changes to db schema as above
5. Frontend Routes:
-fixed formatting, deleted some components around out of scope organizing functionality
6. Sample State:
-updated sample state to reflect subtraction of the category and taggings tables, and changes to user and events categories
